from pathlib import Path
root=Path('/mnt/data/cricket-career-adsense-ready')
PUB='pub-7377609480198522'
ADS=f'''<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-{PUB}" crossorigin="anonymous"></script>'''
nav=[('Home','index.html'),('Play Game','play.html'),('How to Play','how-to-play.html'),('Rules','rules.html'),('Features','features.html'),('Teams','teams.html'),('FAQ','faq.html'),('About','about.html'),('Contact','contact.html'),('Privacy','privacy.html'),('Terms','terms.html')]

def template(title,desc,body,active=''):
    menu=''.join(f'<a class="{"active" if href==active else ""}" href="{href}">{name}</a>' for name,href in nav)
    return f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <meta name="theme-color" content="#07111f">
  <title>{title}</title>
  <meta name="description" content="{desc}">
  <link rel="canonical" href="https://diliptiwari.github.io/{active if active!='index.html' else ''}">
  <link rel="stylesheet" href="styles.css">
  {ADS}
</head>
<body>
<a class="skip" href="#content">Skip to content</a>
<header class="header"><div class="wrap nav"><a class="brand" href="index.html"><span class="logo">CC</span><span>Cricket Career</span></a><nav class="menu" aria-label="Main navigation">{menu}</nav></div></header>
<main id="content">{body}</main>
<footer class="footer"><div class="wrap footer-grid"><div><b>Cricket Career</b><p>A mobile-friendly original cricket game prototype with cinematic toss, field camera, batting, bowling and match highlights.</p><p class="small">This is an independent fan-style cricket game concept. It is not affiliated with any cricket board, league, player, broadcaster or sponsor.</p></div><div><b>Game</b><a href="play.html">Play Game</a><a href="how-to-play.html">How to Play</a><a href="rules.html">Rules</a><a href="teams.html">Teams</a></div><div><b>Site</b><a href="about.html">About</a><a href="contact.html">Contact</a><a href="privacy.html">Privacy Policy</a><a href="terms.html">Terms</a><a href="disclaimer.html">Disclaimer</a></div></div></footer>
</body>
</html>'''

home='''<section class="hero"><div class="wrap grid"><div><div class="eyebrow">Original web cricket game</div><h1 class="h1">Cinematic toss, live field camera, batting, bowling and highlights.</h1><p class="lead">Cricket Career is a lightweight browser cricket game built for mobile and desktop. Select a national-style XI, choose your jersey colour, watch the toss ceremony, enter the field, play shots by style and direction, bowl with speed control, and review key match highlights after the final ball.</p><div class="actions"><a class="btn" href="play.html">Play the prototype</a><a class="btn secondary" href="how-to-play.html">Read how to play</a></div></div><div class="card stadium-card"><div class="stadium"><div class="pitch"></div><span class="mini-player p1"></span><span class="mini-player p2"></span><span class="mini-player p3"></span><span class="mini-player p4"></span></div></div></div></section><section class="section"><div class="wrap"><div class="eyebrow">What is inside</div><h2>Built as a proper site, not a blank game screen</h2><p class="lead">The website includes original gameplay explanations, rules, feature pages, team details, privacy information and clear navigation so users and reviewers can understand the purpose of every page.</p><div class="cards"><article class="card feature"><h3>Toss ceremony</h3><p>Captains and umpire appear on the pitch, the coin is tossed, the camera follows it, and the result is declared before the innings starts.</p></article><article class="card feature"><h3>Batting and bowling</h3><p>Choose Push, Stroke or Loft while batting, swipe to aim, or bowl with length, pace and confidence controls.</p></article><article class="card feature"><h3>Match highlights</h3><p>Fours, sixes, wickets, catches and super saves are saved in a post-match highlight list.</p></article></div></div></section><section class="section"><div class="wrap article"><h2>Pages included for a complete user experience</h2><div class="page-list"><a href="how-to-play.html"><b>How to Play</b><br><span class="small">Controls and match flow.</span></a><a href="rules.html"><b>Rules</b><br><span class="small">Overs, wickets and scoring.</span></a><a href="features.html"><b>Features</b><br><span class="small">Cinematics and gameplay modes.</span></a><a href="teams.html"><b>Teams</b><br><span class="small">Original fictional rosters.</span></a></div></div></section>'''
root.joinpath('index.html').write_text(template('Cricket Career - 3D Web Cricket Game','Play Cricket Career, an original mobile-friendly web cricket game with cinematic toss, batting, bowling, field camera and match highlights.','\n'+home,'index.html'),encoding='utf-8')

play=f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <meta name="theme-color" content="#041018">
  <title>Play Cricket Career - Cinematic Web Cricket Game</title>
  <meta name="description" content="Play the Cricket Career prototype with toss ceremony, jersey selection, batting controls, bowling controls, umpire signals and match highlights.">
  <link rel="canonical" href="https://diliptiwari.github.io/play.html">
  <link rel="stylesheet" href="styles.css">
</head>
<body class="game-body">
<div class="game-shell">
  <div class="game-top"><a class="brand" href="index.html"><span class="logo">CC</span><span>Cricket Career</span></a><div class="actions"><a class="btn secondary" href="index.html">Back to site</a><button id="newMatch" class="btn danger" type="button">New Match</button></div></div>
  <div class="game-layout">
    <section class="canvas-card" aria-label="Cricket game camera">
      <canvas id="gameCanvas" width="1100" height="720"></canvas>
      <div class="hud"><span id="scoreText" class="pill">0/0</span><span id="targetText" class="pill">First innings</span><span id="cameraText" class="pill">Selection Cam</span></div>
      <div id="commentaryText" class="ticker">Select teams and start the match.</div>
    </section>
    <aside class="panel" id="selectionPanel">
      <h2>Match Setup</h2>
      <p class="small">Choose teams, jersey colour and overs. Rosters are original fictional names for copyright-safe gameplay.</p>
      <div class="form-row"><label for="teamSelect">Your team</label><select id="teamSelect"></select></div>
      <div class="form-row"><label for="oppSelect">Opponent</label><select id="oppSelect"></select></div>
      <div class="form-row"><label for="colorSelect">Jersey colour</label><select id="colorSelect"></select></div>
      <div class="form-row"><label for="overSelect">Overs</label><select id="overSelect"><option value="1">1 over</option><option value="2" selected>2 overs</option><option value="5">5 overs</option></select></div>
      <button id="startMatch" class="btn" type="button">Start cinematic match</button>
      <div class="notice" style="margin-top:1rem">AdSense-safe note: this game uses original text, shapes and fictional player names. Do not add copied player photos, official logos or scraped content unless you have rights.</div>
    </aside>
    <aside class="panel hidden" id="tossPanel">
      <h2>Toss</h2>
      <p class="small">Camera shows the umpire and both captains. Choose the call and watch the coin.</p>
      <div class="choice-row"><button id="tossHeads" data-group="tossChoice" class="chip active" type="button">Heads</button><button id="tossTails" data-group="tossChoice" class="chip" type="button">Tails</button></div>
      <h3>If you win toss</h3><div class="choice-row"><button id="chooseBat" class="btn" type="button">Bat first</button><button id="chooseBowl" class="btn secondary" type="button">Bowl first</button></div>
      <p class="small">If opponent wins, their captain will choose automatically.</p>
    </aside>
    <aside class="panel hidden" id="controlPanel">
      <h2>Live Controls</h2>
      <div class="scorebox"><div class="metric"><b id="teamText">Team</b><span>Batting side</span></div><div class="metric"><b id="batterText">Batter</b><span>Striker</span></div><div class="metric"><b id="bowlerText">Bowler</b><span>Current bowler</span></div><div class="metric"><b><span id="confText">35</span>/100</b><span>Bat confidence</span></div></div>
      <h3>Batting</h3><p class="small">Swipe on the field to aim, then choose shot power.</p><div class="choice-row"><button class="chip" data-group="shotChoice" data-shot="Push" type="button">Push</button><button class="chip active" data-group="shotChoice" data-shot="Stroke" type="button">Stroke</button><button class="chip" data-group="shotChoice" data-shot="Loft" type="button">Loft</button></div><button id="playShot" class="btn" type="button">Play shot</button>
      <h3>Bowling</h3><div class="choice-row"><button class="chip active" data-group="bowlChoice" data-bowl="Good Length" type="button">Good Length</button><button class="chip" data-group="bowlChoice" data-bowl="Yorker" type="button">Yorker</button><button class="chip" data-group="bowlChoice" data-bowl="Bouncer" type="button">Bouncer</button><button class="chip" data-group="bowlChoice" data-bowl="Spin" type="button">Spin</button></div>
      <div class="form-row"><label for="speedRange">Delivery speed: <span id="speedValue">135 km/h</span></label><input id="speedRange" type="range" min="70" max="155" value="135"></div><button id="bowlNow" class="btn secondary" type="button">Bowl now</button>
      <h3>Confidence</h3><div class="small">Bat <span id="confText2"></span></div><div class="bar"><i id="confBar"></i></div><div class="small">Bowl <span id="bowlConfText">35</span>/100</div><div class="bar"><i id="bowlConfBar"></i></div><div class="control-row"><button id="specialBtn" class="btn warn" type="button">Special locked</button><button id="nextBall" class="btn secondary" type="button">Continue</button></div>
      <h3>Commentary Log</h3><div id="miniLog"></div>
      <button id="viewHighlights" class="btn secondary" type="button" style="margin-top:.75rem">View highlights</button>
    </aside>
    <aside class="panel hidden" id="highlightPanel"><h2>Highlights</h2><p class="small">Fours, sixes, wickets, catches and boundary saves are saved here.</p><div id="highlightList" class="highlight-list"></div><button class="btn secondary" type="button" onclick="location.reload()">Restart game</button></aside>
    <aside class="panel hidden" id="resultPanel"><h2>Result</h2><p id="resultText"></p><button id="viewHighlights" class="btn" type="button">View highlights</button></aside>
  </div>
</div>
<script src="game.js"></script>
</body>
</html>'''
# Fix duplicate id in result by replacing second occurrence with inline dedicated button generated later via JS not required
play=play.replace('<button id="viewHighlights" class="btn" type="button">View highlights</button>','<button class="btn" type="button" onclick="document.getElementById(\'highlightPanel\').classList.remove(\'hidden\');document.getElementById(\'resultPanel\').classList.add(\'hidden\');">View highlights</button>')
root.joinpath('play.html').write_text(play,encoding='utf-8')

pages={
'how-to-play.html':('How to Play Cricket Career','Learn Cricket Career controls, toss flow, batting, bowling, confidence and highlights.', '''<article class="article"><h1>How to Play Cricket Career</h1><p>Cricket Career is designed as a quick browser cricket match with cinematic presentation. The match begins with team selection, a toss ceremony, player entry, fielding discussion, batting or bowling controls, and post-match highlights.</p><h2>1. Select match setup</h2><p>Choose your team, opponent, jersey colour and match length. The current prototype supports short matches so it works smoothly on GitHub Pages and mobile browsers.</p><h2>2. Watch the toss</h2><p>Select Heads or Tails. The camera moves to the pitch, the coin is tossed, and the umpire declares the result. If your captain wins, you can choose to bat or bowl first.</p><h2>3. Batting controls</h2><ul><li><b>Push:</b> lower risk, useful for singles.</li><li><b>Stroke:</b> balanced option for timing and boundaries.</li><li><b>Loft:</b> high reward but higher wicket risk.</li><li><b>Swipe direction:</b> drag on the field to aim the shot.</li></ul><h2>4. Bowling controls</h2><p>Choose Good Length, Yorker, Bouncer or Spin and set the speed using the delivery speed meter. Each bowler type has a different ideal speed and confidence impact.</p><h2>5. Confidence and special abilities</h2><p>Boundaries and tight bowling increase confidence. Once confidence reaches the unlock level, special abilities such as Power Loft or Perfect Yorker become available.</p><h2>6. Highlights</h2><p>The game stores wickets, fours, sixes and fielding moments in the highlights list so users can review the match story after the result.</p></article>'''),
'rules.html':('Cricket Career Rules','Understand scoring, wickets, overs, innings, toss and match result rules in Cricket Career.', '''<article class="article"><h1>Game Rules</h1><p>The prototype follows simplified cricket rules so matches are fast and easy to play on mobile.</p><h2>Overs and innings</h2><p>A match can be played as 1, 2 or 5 overs per side. Each over has six legal balls. The innings ends when the selected overs are completed or when ten wickets fall.</p><h2>Toss rule</h2><p>The toss decides which captain gets the choice to bat or bowl first. If your team wins the toss, you choose the decision. If the opponent wins, the game makes an automatic decision.</p><h2>Scoring</h2><ul><li>0 runs: dot ball or fielding save.</li><li>1 to 3 runs: running between wickets.</li><li>4 runs: boundary along the ground.</li><li>6 runs: lofted shot over the rope.</li></ul><h2>Wickets</h2><p>Wickets can happen through bowled, caught, edge, LBW or stumping-style events. After a wicket, the next batter gets an entry animation and record card.</p><h2>Match result</h2><p>The side chasing wins if it crosses the target before the innings ends. Otherwise, the defending side wins by runs.</p></article>'''),
'features.html':('Cricket Career Features','Explore cinematic toss, umpire actions, field camera, batting entry, bowling controls and highlight features.', '''<article class="article"><h1>Features</h1><p>Cricket Career focuses on presentation and match feeling, not only button tapping.</p><h2>Cinematic scenes</h2><p>The game includes team selection, toss camera, coin toss animation, umpire decision, batter walk-in, fielding huddle, live broadcast camera, wicket entry and post-match result scene.</p><h2>Umpire actions</h2><p>The umpire can raise both arms for a six, signal a wicket, stand behind the bowler and appear during review-style moments.</p><h2>Batting model</h2><p>Batters have roles and ratings. Shot selection changes risk and reward. Swipe direction decides where the ball is aimed.</p><h2>Bowling model</h2><p>Bowlers have skill ratings. Speed, delivery type and confidence decide whether the ball is accurate, loose, wicket-taking or easy to score.</p><h2>Fielding model</h2><p>Fielders are shown around the ground and can create dot balls, super saves and catching moments.</p><h2>Highlights model</h2><p>Important events are saved so the player can view the match story after the game.</p></article>'''),
'pitch-report.html':('Pitch and Weather Guide','Learn how pitch and weather commentary affects match atmosphere in Cricket Career.', '''<article class="article"><h1>Pitch and Weather Guide</h1><p>Before every match, commentary describes the weather and pitch. These reports add match atmosphere and help users feel like they are watching a broadcast.</p><h2>Weather commentary</h2><p>The weather text can mention breeze, dew, cloud cover or dry conditions. This helps set the scene before the toss and innings.</p><h2>Pitch commentary</h2><p>Pitch text can describe bounce, seam movement, spin help or flat batting conditions. Future versions can connect pitch type directly to gameplay calculations.</p><h2>Why this page exists</h2><p>This page gives users meaningful information about the match environment and helps the website provide useful original content beyond the game canvas.</p></article>'''),
'controls.html':('Controls Guide','Cricket Career controls for batting, bowling, swipe aiming and confidence abilities.', '''<article class="article"><h1>Controls Guide</h1><h2>Touch and mouse aiming</h2><p>Drag or swipe over the field to select the batting direction. The commentary confirms the direction after a valid swipe.</p><h2>Shot buttons</h2><p>Push is safe, Stroke is balanced, and Loft is aggressive. Choosing the right shot matters because each option changes the scoring and wicket chance.</p><h2>Bowling buttons</h2><p>Good Length is balanced, Yorker is attacking, Bouncer is aggressive and Spin uses lower speed. The speed slider decides whether the delivery is close to the ideal ball.</p><h2>Special button</h2><p>When confidence is high enough, the special button triggers a powerful batting or bowling ability.</p></article>'''),
'career-mode.html':('Career Mode Plan','Future career mode roadmap for Cricket Career including player growth and unlocks.', '''<article class="article"><h1>Career Mode Plan</h1><p>The current version is a playable prototype. The planned career mode will allow users to grow a custom player over multiple matches.</p><h2>Planned progression</h2><ul><li>Player experience after every match.</li><li>Unlockable batting and bowling skills.</li><li>Confidence-based special abilities.</li><li>Match records, best scores and wicket milestones.</li></ul><h2>Future match flow</h2><p>Future versions can add tournaments, team selection, league tables, player form, injury/fatigue, stadium choices and saved profiles.</p></article>'''),
'players.html':('Player Ratings Guide','How Cricket Career uses fictional player roles and ratings.', '''<article class="article"><h1>Player Ratings Guide</h1><p>Every player in this prototype has an original fictional name, a role, a batting rating and a bowling rating. This keeps the game independent and avoids copying protected player likenesses.</p><h2>Batting rating</h2><p>A higher batting rating increases the chance of clean contact and reduces wicket risk.</p><h2>Bowling rating</h2><p>A higher bowling rating improves accuracy and wicket-taking chance.</p><h2>Roles</h2><p>Roles such as opener, anchor, finisher, fast bowler, spinner and all-rounder create different gameplay expectations.</p></article>'''),
'gameplay-tips.html':('Gameplay Tips','Tips to score more runs, bowl better and unlock special abilities in Cricket Career.', '''<article class="article"><h1>Gameplay Tips</h1><h2>Batting tips</h2><ul><li>Use Push early if wickets are falling.</li><li>Use Stroke when confidence is building.</li><li>Use Loft after confidence improves or when the target requires big shots.</li><li>Swipe direction before playing a shot to aim toward gaps.</li></ul><h2>Bowling tips</h2><ul><li>Use Good Length when you want control.</li><li>Use Yorker at higher speed for wicket pressure.</li><li>Use Spin at lower speed for variation.</li><li>Build bowler confidence with dot balls.</li></ul></article>'''),
'updates.html':('Game Updates','Latest update notes and roadmap for Cricket Career.', '''<article class="article"><h1>Game Updates</h1><h2>Current version</h2><p>This update adds an AdSense-ready site structure, original content pages, playable cricket prototype, cinematic toss, batter entry, field discussion, bowling controls and post-match highlights.</p><h2>Next planned improvements</h2><ul><li>Better player animations.</li><li>Saved career profile.</li><li>More stadium themes.</li><li>More commentary lines.</li><li>Replay camera for every highlight.</li></ul></article>'''),
'faq.html':('Cricket Career FAQ','Frequently asked questions about Cricket Career browser game, teams, ads, privacy and gameplay.', '''<article class="article"><h1>Frequently Asked Questions</h1><h2>Is Cricket Career free?</h2><p>Yes, the prototype is free to play in a browser.</p><h2>Does the game use real players?</h2><p>No. The current version uses original fictional player names and ratings. This is safer for publishing because it avoids copying player likenesses, official rosters or protected branding.</p><h2>Can I play on mobile?</h2><p>Yes. The layout is responsive and the canvas supports touch swipes.</p><h2>Why are there content pages?</h2><p>The pages explain the game, rules and controls so visitors get helpful information and reviewers can understand the purpose of the site.</p><h2>Does the game collect personal data?</h2><p>The static prototype does not require login and does not store personal details on a server.</p></article>'''),
'about.html':('About Cricket Career','About the Cricket Career original web cricket game project.', '''<article class="article"><h1>About Cricket Career</h1><p>Cricket Career is an independent browser-based cricket game concept. The goal is to create a lightweight cricket experience that works on mobile, desktop and static hosting such as GitHub Pages.</p><p>The game is focused on cinematic presentation: toss ceremony, pitch camera, player walk-in, fielding huddle, batting shots, bowling choices, umpire actions and match highlights.</p><h2>Independent project</h2><p>This project is not affiliated with any cricket board, tournament, league, player, broadcaster or sponsor. All rosters in the prototype are fictional and used only for gameplay demonstration.</p><h2>Why web first?</h2><p>A web version is easy to share, test and improve. It also allows quick updates without asking users to install an app.</p></article>'''),
'contact.html':('Contact Cricket Career','Contact page for Cricket Career feedback, bug reports and suggestions.', '''<article class="article"><h1>Contact</h1><p>Use this page for feedback, bug reports or feature suggestions about Cricket Career.</p><div class="notice"><b>Before publishing:</b> replace the placeholder email below with your preferred public contact email.</div><h2>Email</h2><p><a href="mailto:your-email@example.com">your-email@example.com</a></p><h2>Feedback ideas</h2><ul><li>Gameplay bug reports.</li><li>Suggestions for new modes.</li><li>Mobile display issues.</li><li>Commentary improvements.</li></ul></article>'''),
'privacy.html':('Privacy Policy - Cricket Career','Privacy policy for Cricket Career static web game and advertising disclosures.', '''<article class="article"><h1>Privacy Policy</h1><p>Cricket Career is a static browser game. The current version does not require account creation and does not ask users to submit personal information.</p><h2>Information we collect</h2><p>The game itself runs in the browser and does not send gameplay data to a private server. If analytics or advertising tools are added later, those services may collect information according to their own policies.</p><h2>Cookies and advertising</h2><p>This website may use Google AdSense or similar advertising services after approval. Advertising providers may use cookies or device identifiers to show, limit or measure ads.</p><h2>Third-party links</h2><p>The site may link to external resources. We are not responsible for the privacy practices of other websites.</p><h2>Children</h2><p>The game is intended as general entertainment. It does not knowingly collect personal information from children.</p><h2>Contact</h2><p>For privacy questions, update this page with your public contact email before publishing.</p></article>'''),
'terms.html':('Terms and Conditions - Cricket Career','Terms and conditions for using the Cricket Career web game.', '''<article class="article"><h1>Terms and Conditions</h1><p>By using Cricket Career, you agree to use the website and game for personal entertainment and testing purposes.</p><h2>Use of the game</h2><p>You may play the game in your browser. Do not misuse the site, attempt to break the service or copy the project in a way that misrepresents ownership.</p><h2>Content ownership</h2><p>The website text, design, game logic and fictional rosters in this package are original project content. Official cricket logos, player photos or protected assets are not included.</p><h2>No warranty</h2><p>The game is provided as a prototype. It may contain bugs or incomplete features.</p><h2>Changes</h2><p>The site may be updated with new features, rules, pages or policies.</p></article>'''),
'disclaimer.html':('Disclaimer - Cricket Career','Independent project and copyright disclaimer for Cricket Career.', '''<article class="article"><h1>Disclaimer</h1><p>Cricket Career is an independent cricket-inspired game project. It is not affiliated with, endorsed by or sponsored by any cricket board, league, team, broadcaster, sponsor or real player.</p><h2>Fictional rosters</h2><p>The current prototype uses fictional player names and ratings. Country-style team names are used only to make match selection understandable.</p><h2>No copied assets</h2><p>The game uses browser-drawn shapes, original text and simple animations. Do not upload copyrighted photos, logos, broadcast footage, commentary clips or player likenesses unless you own the rights or have permission.</p><h2>Prototype status</h2><p>This game is a development prototype. Features may change as the game model improves.</p></article>'''),
'teams.html':('Cricket Career Teams','Original national-style teams and fictional player rosters in Cricket Career.', '''<article class="article"><h1>Teams</h1><p>The current prototype includes national-style teams with fictional rosters. This gives a cricket feel without copying official squads or player likenesses.</p><h2>Available teams</h2><ul><li>India XI</li><li>Australia XI</li><li>England XI</li><li>South Africa XI</li><li>New Zealand XI</li><li>Pakistan XI</li><li>Sri Lanka XI</li><li>Bangladesh XI</li></ul><h2>Why fictional players?</h2><p>Using fictional names, original ratings and original animations helps keep the project independent and safer for advertising review. Licensed real-player assets can be added only when proper rights are available.</p></article>'''),
}
for href,(title,desc,body) in pages.items():
    root.joinpath(href).write_text(template(title,desc,'<section class="content"><div class="wrap">'+body+'</div></section>',href),encoding='utf-8')
